### ISSUE TITLE
Clean Iraq Website - Review Notes 

### ISSUE THREAD

**Issue by MustafaMerie** [Ninnoss/Clean-Iraq-Website#26]
I'm really impressed! Very organized and well-written code! Great work, team! I can see the huge effort you all have put into it. Well done.

However, Here are some general review points, that would make your code even better:

#### Code Formatting:
-   Ensure consistent code formatting throughout the project. The team should stick to a formatting tool and make sure to format the code before any commits.

#### Remove Unused Code in Production:
-   Remove any unused code from the production version of your project to keep it clean and optimized.

#### Don't repeat yourself:
- If you check the `ContactForm.jsx`, `DesktopMenus.jsx`, `Footer.jsx` and `MobileNavbar.jsx`. You'll notice repetitive code blocks. Instead of duplicating code, consider creating a list of items and using mapping to assemble them.

example:
```javascript
  const navLinks = [
    { to: '/', text: 'navigation.home' },
    { to: '/about', text: 'navigation.about' },
    { to: '/campaigns', text: 'navigation.campaigns' },
    { to: '/projects', text: 'navigation.projects' },
    { to: '/map', text: 'navigation.map' },
    { to: '/blogs', text: 'navigation.blogs' },
  ];

 {navLinks.map((link, index) => (
    <li key={index}>
         <NavLink onClick={scrollToTop}  to={link.to} >
             {t(link.text)}
         </NavLink>
    </li>
))}
``` 
Other than that, your work is perfect! 
Please feel free to reach out If something is confusing or you want to talk more.

**Comment by Ninnoss** [comment]
Thank you for your kind words, dear Mustafa! Indeed there is still room for many improvements for refactoring and possible further optimizations, however, due to the time constraints of the projects we couldn't polish everything up in time. Will definitely use your notes and recommendations in future projects!
